server:
  port: 8080
spring:
  application:
    name: devices
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
jwt:
  secret: BWXt6ZHbMT67bAfcFP2zT42rQ48grQuG7VTMtHbgmxjTVF6QWoQvRmZ4QjCfqDFH
logging:
  file:
    name: 'app.log'
  #    path: '.'
  structured:
    format:
      file: logstash
    json:
      add:
        corpname: mycorp
  level:
    org:
      springframework:
        security: debug
#    root: error
info:
  app:
    name: MyApp
    version: '@project.version@'
    description: Production API