server:
  port: 8080
spring:
  application:
    name: devices
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true